version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: /.*\.nupkg/
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: <PUT API KEY HERE>
  artifact: 
  on:
    branch: master